set_property PACKAGE_PIN D23 [get_ports clk100M]
set_property PACKAGE_PIN E22 [get_ports hdmi_tx_cec]
set_property PACKAGE_PIN D21 [get_ports hdmi_tx_clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports clk100M]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_cec]
set_property IOSTANDARD LVCMOS33 [get_ports rstbt]
set_property PACKAGE_PIN A23 [get_ports hdmi_tx_d0_p]
set_property PACKAGE_PIN C21 [get_ports hdmi_tx_d1_p]
set_property PACKAGE_PIN B20 [get_ports hdmi_tx_d2_p]
set_property PACKAGE_PIN A10 [get_ports {bt[0]}]
set_property PACKAGE_PIN A17 [get_ports {bt[1]}]
set_property PACKAGE_PIN A19 [get_ports {bt[2]}]
set_property PACKAGE_PIN A18 [get_ports {bt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]

set_property PACKAGE_PIN E16 [get_ports {led_r[0]}]
set_property PACKAGE_PIN E17 [get_ports {led_r[1]}]
set_property PACKAGE_PIN F19 [get_ports {led_r[2]}]
set_property PACKAGE_PIN C14 [get_ports {led_r[3]}]
set_property PACKAGE_PIN D15 [get_ports {led_r[4]}]
set_property PACKAGE_PIN C16 [get_ports {led_r[5]}]
set_property PACKAGE_PIN D18 [get_ports {led_r[6]}]
set_property PACKAGE_PIN C18 [get_ports {led_r[7]}]
set_property PACKAGE_PIN L23 [get_ports rstbt]
set_property PACKAGE_PIN E11 [get_ports {sw[0]}]
set_property PACKAGE_PIN E12 [get_ports {sw[1]}]
set_property PACKAGE_PIN E15 [get_ports {sw[2]}]
set_property PACKAGE_PIN G14 [get_ports {sw[3]}]
set_property PACKAGE_PIN B11 [get_ports {sw[4]}]
set_property PACKAGE_PIN C11 [get_ports {sw[5]}]
set_property PACKAGE_PIN C12 [get_ports {sw[6]}]
set_property PACKAGE_PIN B12 [get_ports {sw[7]}]

create_clock -period 10.000 -name clk100M -waveform {0.000 5.000} [get_ports clk100M]
create_clock -period 10.000 -name hdmi_rx_clk_p -waveform {0.000 5.000} [get_ports hdmi_rx_clk_p]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_rx_cec]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_rx_hpd]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_rx_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_rx_sda]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_hpdn]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_sda]
set_property PACKAGE_PIN F23 [get_ports hdmi_rx_cec]
set_property PACKAGE_PIN G24 [get_ports hdmi_rx_clk_p]
set_property PACKAGE_PIN F25 [get_ports hdmi_rx_d0_p]
set_property PACKAGE_PIN D26 [get_ports hdmi_rx_d1_p]
set_property PACKAGE_PIN E25 [get_ports hdmi_rx_d2_p]
set_property PACKAGE_PIN E21 [get_ports hdmi_rx_hpd]
set_property PACKAGE_PIN F22 [get_ports hdmi_rx_scl]
set_property PACKAGE_PIN E23 [get_ports hdmi_rx_sda]
set_property PACKAGE_PIN G21 [get_ports hdmi_tx_hpdn]
set_property PACKAGE_PIN D24 [get_ports hdmi_tx_scl]
set_property PACKAGE_PIN C24 [get_ports hdmi_tx_sda]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN M21 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN N21 [get_ports uart_rtl_0_rxd]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk100M_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {histogram_top/hisitogram_calc/external_data_rd[0]} {histogram_top/hisitogram_calc/external_data_rd[1]} {histogram_top/hisitogram_calc/external_data_rd[2]} {histogram_top/hisitogram_calc/external_data_rd[3]} {histogram_top/hisitogram_calc/external_data_rd[4]} {histogram_top/hisitogram_calc/external_data_rd[5]} {histogram_top/hisitogram_calc/external_data_rd[6]} {histogram_top/hisitogram_calc/external_data_rd[7]} {histogram_top/hisitogram_calc/external_data_rd[8]} {histogram_top/hisitogram_calc/external_data_rd[9]} {histogram_top/hisitogram_calc/external_data_rd[10]} {histogram_top/hisitogram_calc/external_data_rd[11]} {histogram_top/hisitogram_calc/external_data_rd[12]} {histogram_top/hisitogram_calc/external_data_rd[13]} {histogram_top/hisitogram_calc/external_data_rd[14]} {histogram_top/hisitogram_calc/external_data_rd[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {histogram_top/hisitogram_calc/external_addr_rd[0]} {histogram_top/hisitogram_calc/external_addr_rd[1]} {histogram_top/hisitogram_calc/external_addr_rd[2]} {histogram_top/hisitogram_calc/external_addr_rd[3]} {histogram_top/hisitogram_calc/external_addr_rd[4]} {histogram_top/hisitogram_calc/external_addr_rd[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list histogram_top/hisitogram_calc/n_0_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list histogram_top/hisitogram_calc/n_0_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list histogram_top/s_axi_arvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk100M_IBUF_BUFG]
